namespace Frame.Domain.Common;

/// <summary>
/// Base class for every entity stored in the database.
/// Holds the fields that all tables share.
/// </summary>
public abstract class BaseEntity
{
    /// <summary>
    /// Primary key. Generated by the database, never set from outside.
    /// </summary>
    public int Id { get; protected set; }

    /// <summary>
    /// When the row was created (UTC). Set automatically by the
    /// database layer on insert, so no service can fake or forget it.
    /// </summary>
    public DateTime CreatedAt { get; private set; }
}